# Site settings
title: DALI 2016 - Data Learning and Inference
banner: sestri.jpeg
permalink: "/:categories/:title.html"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: dali

baseurl: "/dali2016" # the subpath of your site, e.g. /blog/
url: "http://dalimeeting.org" # the base hostname & protocol for your site
twitter_username: 
github_username:  dalimeeting
author:
  name: DALI
  
ghub:
  edit: true
  repository: dali2016

conference:
  draft: False # set to True if the programme is draft only.
  full_name: Data Learning and Inference
  name: Data Learning and Inference
  short_name: DALI
  year: 2016
  venue:
  location: Sestri Levante, Italy
  dates:
  - 2016-03-30
  - 2016-03-31
  - 2016-04-01
  hosts:
  general:
  - given: Thomas
    family: Hofmann
    url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
    institute: ETH Zurich
  workshop:
  - given: Neil D.
    family: Lawrence
    url: "http://inverseprobability.com"
    institute: University of Sheffield
  symposium:
  - given: Zoubin
    family: Ghaharamani
    url: "http://mlg.eng.cam.ac.uk/zoubin/"
    institute: University of Cambridge
  local:
  - given: Lorenzo
    family: Rosasco
    url: "http://web.mit.edu/lrosasco/www/"
    institute: University of Genova and MIT
  assistants:
  - given: Carlo
    family: Ciliberto
    url: "https://it.linkedin.com/in/carlo-ciliberto-174a98105"
    institute: IIT and MIT
  - given: Sabrina
    family: Nepozitek
    url: "http://www.da.inf.ethz.ch/people/SabrinaNepozitek/"
    institute: ETH Zurich
  steering:
  - given: Zoubin
    family: Ghaharamani
    url: "http://mlg.eng.cam.ac.uk/zoubin/"
    institute: University of Cambridge
  - given: Thomas
    family: Hofmann
    url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
    institute: ETH Zurich
  - given: Neil
    family: Lawrence
    url: "http://inverseprobability.com"
    institute: University of Sheffield
  - given: Bernhard
    family: Schölkopf
    positon: Chair
    url: "http://ei.is.tuebingen.mpg.de/person/bs"
    institute: MPI Tübingen
  sponsors:
  - name: Max-Planck-ETH Center for Learning Systems
    url: "http://learning-systems.org/"
baseurl: "/dali2016" # the subpath of your site, e.g. /blog/
url: "http://dalimeeting.org" # the base hostname & protocol for your site
youtube:
  height: 315
  width: 560
twitter_username: 
github_username:  dalimeeting
future: true

# Build settings
markdown: kramdown
